"""empty message

Revision ID: d4465a7be4e3
Revises: 49f25a1006f8
Create Date: 2018-10-13 18:36:05.030634

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd4465a7be4e3'
down_revision = '49f25a1006f8'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint(None, 'stock', ['symbol'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'stock', type_='unique')
    # ### end Alembic commands ###
