"""empty message

Revision ID: e803609a08e4
Revises: 49f25a1006f8
Create Date: 2018-11-04 10:44:59.500027

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e803609a08e4'
down_revision = '49f25a1006f8'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index(op.f('ix_stock_id'), 'stock', ['id'], unique=False)
    op.create_index(op.f('ix_stock_symbol'), 'stock', ['symbol'], unique=False)
    op.drop_index('ix_todo_todo', table_name='todo')
    op.create_index(op.f('ix_todo_todo'), 'todo', ['todo'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_todo_todo'), table_name='todo')
    op.create_index('ix_todo_todo', 'todo', ['todo'], unique=1)
    op.drop_index(op.f('ix_stock_symbol'), table_name='stock')
    op.drop_index(op.f('ix_stock_id'), table_name='stock')
    # ### end Alembic commands ###
